import * as DocumentPicker from 'expo-document-picker';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Field, PrimaryButton, Screen, SectionTitle } from '@/components/UI';
import { useApp } from '@/context/AppContext';
import { colors, radius } from '@/theme';

export default function SwapNew(){
  const params=useLocalSearchParams<{employeeId?:string}>();const{data,session,createSwap}=useApp();const fixedEmployee=session?.role==='employee'?session.employeeId:params.employeeId;const[employeeId,setEmployeeId]=useState(fixedEmployee??data.employees[0]?.id??'');const[epiId,setEpiId]=useState(data.epis[0]?.id??'');const[reason,setReason]=useState('Desgaste');const[description,setDescription]=useState('');const[photoUri,setPhotoUri]=useState<string|undefined>();const[photoName,setPhotoName]=useState('Sem foto');const[saving,setSaving]=useState(false);
  const pick=async()=>{const result=await DocumentPicker.getDocumentAsync({type:'image/*',copyToCacheDirectory:true});if(!result.canceled){setPhotoUri(result.assets[0]?.uri);setPhotoName(result.assets[0]?.name??'Foto anexada');}};
  const save=async()=>{if(!employeeId||!epiId||!reason.trim()||!description.trim())return Alert.alert('Solicitação incompleta','Informe EPI, motivo e descrição.');setSaving(true);await createSwap({employeeId,epiId,reason,description,photoUri});setSaving(false);Alert.alert('Solicitação criada','A troca foi registrada como Pendente.',[{text:'OK',onPress:()=>router.back()}]);};
  return <Screen>{session?.role==='admin'?<><SectionTitle>Colaborador</SectionTitle><View style={{gap:8}}>{data.employees.filter(e=>e.status==='Ativo').map(e=><Pressable key={e.id} onPress={()=>setEmployeeId(e.id)} style={[styles.choice,employeeId===e.id&&styles.active]}><Text style={[styles.choiceText,employeeId===e.id&&styles.activeText]}>{e.name}</Text><Text style={styles.meta}>{e.registration} • {e.sector}</Text></Pressable>)}</View></>:null}<SectionTitle>EPI</SectionTitle><View style={{gap:8}}>{data.epis.map(e=><Pressable key={e.id} onPress={()=>setEpiId(e.id)} style={[styles.choice,epiId===e.id&&styles.active]}><Text style={[styles.choiceText,epiId===e.id&&styles.activeText]}>{e.name}</Text><Text style={styles.meta}>CA {e.ca} • saldo {e.stock}</Text></Pressable>)}</View><Field label="Motivo" value={reason} onChangeText={setReason}/><Field label="Descrição" value={description} onChangeText={setDescription} multiline/><Pressable onPress={pick} style={styles.photo}><Text style={styles.photoTitle}>Adicionar foto opcional</Text><Text style={styles.meta}>{photoName}</Text></Pressable><PrimaryButton label="Criar solicitação" icon="swap-horizontal" loading={saving} onPress={save}/></Screen>;
}
const styles=StyleSheet.create({choice:{padding:13,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:'#fff'},active:{borderColor:colors.blue,backgroundColor:'#EAF1FF'},choiceText:{fontWeight:'800',color:colors.text},activeText:{color:colors.blue},meta:{color:colors.muted,fontSize:12,marginTop:3},photo:{padding:14,borderRadius:radius.md,borderWidth:1,borderStyle:'dashed',borderColor:'#F3C279',backgroundColor:'#FFF9EE'},photoTitle:{color:'#9A6700',fontWeight:'900'}});
